# Generated by Django 5.0 on 2024-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exemplos',
            new_name='Exemplo',
        ),
    ]
