# Generated by Django 5.0 on 2024-10-07 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_exemplos_exemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('data_nascimento', models.DateTimeField()),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('posicao', models.CharField(max_length=20)),
                ('qualidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('cartoes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('suspenso', models.BooleanField(default=False)),
            ],
        ),
    ]
