# Generated by Django 5.0 on 2024-10-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_jogador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name_plural': 'sadkjashdkjas'},
        ),
    ]
