# Generated by Django 5.0 on 2024-10-14 12:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_jogador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(max_length=10, verbose_name='Passaport Number')),
                ('issue_date', models.DateField(default=datetime.datetime.fromtimestamp, verbose_name='Data de Criação')),
                ('expiration_date', models.DateField(verbose_name='Data de Vencimento')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='biblioteca.person')),
            ],
        ),
    ]
