# Generated by Django 5.0 on 2024-10-21 14:41

import biblioteca.models.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_reporter_alter_passport_issue_date_alter_person_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='exemplo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='exemplo',
            name='cod',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), biblioteca.models.validators.CodValidator]),
        ),
        migrations.AddField(
            model_name='exemplo',
            name='nome',
            field=models.CharField(default='sem nome', max_length=15, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.reporter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='ExemploDAO',
            fields=[
                ('basemanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.basemanager')),
            ],
            bases=('biblioteca.basemanager',),
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('magazine', models.ManyToManyField(to='biblioteca.magazine')),
            ],
        ),
    ]
