# Generated by Django 5.0 on 2024-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='gender',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='artista',
            name='follower',
            field=models.IntegerField(default=0, verbose_name='Número de Seguidores'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nr_album',
            field=models.IntegerField(default=1, verbose_name='Quantidade de Albuns'),
        ),
    ]
