# Generated by Django 5.0 on 2024-10-24 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincloud', '0002_rename_gender_artista_genre_alter_artista_follower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome da Playlist')),
                ('description', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descrição da playlist')),
                ('create_date', models.DateField(auto_now=True, verbose_name='Data de Criação')),
                ('nr_likes', models.IntegerField(default=0, verbose_name='Numero de likes')),
                ('duration', models.TimeField(verbose_name='Tempo total da playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome da Musica')),
                ('leter', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Letra da Musica')),
                ('date_upload', models.DateField(verbose_name='Data do Lançamento')),
                ('nr_likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Numero de likes')),
                ('duration', models.TimeField(verbose_name='Duração da musica')),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ELETONICA', 'Eletronica'), ('PAGODE', 'Pagode'), ('ROCK', 'Rock'), ('RAP', 'Rap'), ('SAMBA', 'Samba')], max_length=10, verbose_name='Genero da Musica')),
                ('album', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome do Album')),
                ('nr_plays', models.IntegerField(verbose_name='Numero de plays')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincloud.artista', verbose_name='Artista responsavel')),
                ('playlist', models.ManyToManyField(to='maincloud.playlist', verbose_name='Playlists')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
