# Generated by Django 5.0 on 2024-10-24 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincloud', '0003_playlist_musica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='date_upload',
            field=models.DateField(auto_now=True, verbose_name='Data do Lançamento'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='leter',
            field=models.CharField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Letra da Musica'),
        ),
    ]
